### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Ivan-Kuzmichev** [IsraelAdura/go-postgres-jwt-react-starter#2]
Hello, please help to deal with the error during Assembly.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x20 pc=0x509d48]

**Comment by Ivan-Kuzmichev** [comment]
full error code:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x20 pc=0x509d48]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
        c:/go/src/database/sql/sql.go:1132 +0x48
database/sql.(*DB).PingContext(0x0, 0xb75540, 0xc00001e028, 0x3e, 0x0)
        c:/go/src/database/sql/sql.go:782 +0x97
database/sql.(*DB).Ping(...)
        c:/go/src/database/sql/sql.go:800
github.com/goapi/server/db.Connect()
        D:/Progects/goapi/server/db/db.go:19 +0x110
main.init.0()
        D:/Progects/goapi/server/main.go:13 +0x27
PS>go build .\server\main.go
goapi master *% $ .\main.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x20 pc=0x509d48]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
        c:/go/src/sync/mutex.go:74
database/sql.(*DB).conn(0x0, 0xb754a0, 0xc00001e028, 0x1, 0x1b0008, 0x0, 0xc0001bbd78)
        c:/go/src/database/sql/sql.go:1132 +0x48
database/sql.(*DB).query(0x0, 0xb754a0, 0xc00001e028, 0xaaec47, 0x110, 0x0, 0x0, 0x0, 0xc0001bd101, 0xc0001d65b0, ...)
        c:/go/src/database/sql/sql.go:1565 +0x6d
database/sql.(*DB).QueryContext(0x0, 0xb754a0, 0xc00001e028, 0xaaec47, 0x110, 0x0, 0x0, 0x0, 0x3e, 0xc0001bd0c0, ...)
        c:/go/src/database/sql/sql.go:1547 +0xd8
database/sql.(*DB).Query(...)
        c:/go/src/database/sql/sql.go:1561
github.com/goapi/server/db.CreateUsersTable()
        D:/Progects/goapi/server/db/userschema.go:5 +0x72
github.com/goapi/server/db.Connect()
        D:/Progects/goapi/server/db/db.go:24 +0xf0
main.init.0()
        D:/Progects/goapi/server/main.go:13 +0x27
